When the default (or command-line) family + wiki is not Public, getSite() tries to log in before completely loading the wikipedia module, causing a NameError :
( python login.py )
Traceback (most recent call last):
 File "\login.py", line 49, in <module>
   import wikipedia, config
 File "\wikipedia.py", line 6041, in <module>
   getSite()
 File "\wikipedia.py", line 5930, in getSite
   ret.forceLogin()
 File "\wikipedia.py", line 4178, in forceLogin
   if not self.loggedInAs(sysop = sysop):
 File "\wikipedia.py", line 4170, in loggedInAs
   self._load(sysop = sysop)
 File "\wikipedia.py", line 4756, in _load
   text = self.getUrl(url, sysop = sysop)
 File "\wikipedia.py", line 4438, in getUrl
   uo = MyURLopener()
NameError: global name 'MyURLopener' is not defined

fixing this introducing a noLogin parameter in getSite